"""Initial migration with ratings and other tables

Revision ID: 60b25edb2482
Revises: 
Create Date: 2025-05-14 18:53:13.288089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60b25edb2482'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adventure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adventure_name', sa.String(length=255), nullable=False),
    sa.Column('adults', sa.Integer(), nullable=False),
    sa.Column('children', sa.Integer(), nullable=False),
    sa.Column('pets', sa.Integer(), nullable=False),
    sa.Column('choice', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_rating', sa.Integer(), nullable=False),
    sa.Column('food_rating', sa.Integer(), nullable=False),
    sa.Column('attractions_rating', sa.Integer(), nullable=False),
    sa.Column('accommodation_rating', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('selected_state', sa.String(length=50), nullable=False),
    sa.Column('recommendation_1', sa.String(length=200), nullable=True),
    sa.Column('recommendation_2', sa.String(length=200), nullable=True),
    sa.Column('recommendation_3', sa.String(length=200), nullable=True),
    sa.Column('recommendation_4', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Username'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_selection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=True),
    sa.Column('answer_1', sa.String(length=100), nullable=True),
    sa.Column('answer_2', sa.String(length=100), nullable=True),
    sa.Column('answer_3', sa.String(length=100), nullable=True),
    sa.Column('answer_4', sa.String(length=100), nullable=True),
    sa.Column('answer_5', sa.String(length=100), nullable=True),
    sa.Column('adventure_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['adventure_id'], ['adventure.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_selection')
    op.drop_table('user')
    op.drop_table('recommendations')
    op.drop_table('ratings')
    op.drop_table('adventure')
    # ### end Alembic commands ###
