"""Ratings db

Revision ID: a5629f15c52d
Revises: 
Create Date: 2025-05-15 12:27:03.477883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5629f15c52d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_rating', sa.Integer(), nullable=False),
    sa.Column('food_rating', sa.Integer(), nullable=False),
    sa.Column('attractions_rating', sa.Integer(), nullable=False),
    sa.Column('accommodation_rating', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ratings')
    # ### end Alembic commands ###
