"""Add recommendation_id to Ratings model

Revision ID: ac7b4a60d0c6
Revises: fbfa263f0bd7
Create Date: 2025-05-15 21:20:46.873143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac7b4a60d0c6'
down_revision = 'fbfa263f0bd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('dateofbirth', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Username'),
    sa.UniqueConstraint('email')
    )
    op.create_table('adventure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adventure_name', sa.String(length=255), nullable=False),
    sa.Column('adults', sa.Integer(), nullable=False),
    sa.Column('children', sa.Integer(), nullable=False),
    sa.Column('pets', sa.Integer(), nullable=False),
    sa.Column('choice', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_selection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=True),
    sa.Column('answer_1', sa.String(length=100), nullable=True),
    sa.Column('answer_2', sa.String(length=100), nullable=True),
    sa.Column('answer_3', sa.String(length=100), nullable=True),
    sa.Column('answer_4', sa.String(length=100), nullable=True),
    sa.Column('answer_5', sa.String(length=100), nullable=True),
    sa.Column('adventure_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['adventure_id'], ['adventure.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=False),
    sa.Column('selected_state', sa.String(length=50), nullable=False),
    sa.Column('recommendation_1', sa.String(length=200), nullable=True),
    sa.Column('recommendation_2', sa.String(length=200), nullable=True),
    sa.Column('recommendation_3', sa.String(length=200), nullable=True),
    sa.Column('recommendation_4', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['user_selection.session_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recommendation_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'recommendations', ['recommendation_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('recommendation_id')

    op.drop_table('recommendations')
    op.drop_table('user_selection')
    op.drop_table('adventure')
    op.drop_table('user')
    # ### end Alembic commands ###
