"""Add recommendation_id to Ratings model

Revision ID: ac7b4a60d0c6
Revises: fbfa263f0bd7
Create Date: 2025-05-15 21:20:46.873143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac7b4a60d0c6'
down_revision = 'fbfa263f0bd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recommendation_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('ratings_reccs_rs', 'recommendations', ['recommendation_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('recommendation_id')

    op.drop_table('recommendations')
    op.drop_table('user_selection')
    op.drop_table('adventure')
    op.drop_table('user')
    # ### end Alembic commands ###
