"""updating w overall rating column

Revision ID: fbfa263f0bd7
Revises: a5629f15c52d
Create Date: 2025-05-15 13:08:47.608358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbfa263f0bd7'
down_revision = 'a5629f15c52d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overall_rating', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_column('overall_rating')

    # ### end Alembic commands ###
